syntax = "proto3";

option java_package = "com.wedgess.luas.data.model";
option java_multiple_files = true;


message UserPreferences {
    string selectedGreenLineStation = 1;
    string selectedRedLineStation = 2;
    string selectedDartStation = 3;
    bool locationPermissionRequested = 4;
    bool notificationPermissionRequested = 5;
    bool locationPermissionRationaleShown = 6;
    bool ignoreLocationPermission = 7;
    bool ignoreNotificationPermission = 8;
    Transport transportType = 9;

    enum Transport {
        LUAS = 0;
        DART = 1;
    }
}
